//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rose.VExtension.Server.Models.DbInteraction
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PluginsContainer : DbContext
    {
        public PluginsContainer()
            : base("name=PluginsContainer")
        {

            Plugins = Set<Plugin>();
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            //throw new UnintentionalCodeFirstException();
        }
    
        internal virtual DbSet<Plugin> Plugins { get; set; }
        public virtual DbSet<ResourceToken> ResourceTokens { get; set; }
        public virtual DbSet<StorageItem> StorageItems { get; set; }
        public virtual DbSet<PluginAssociation> PluginAssociationSet { get; set; }
        public virtual DbSet<Test> TestSet { get; set; }
        public virtual DbSet<PluginFileSystem> PluginFileSystems { get; set; }
        public virtual DbSet<PluginPackage> PluginPackages { get; set; }
        public virtual DbSet<Transaction> TransactionSet { get; set; }
    }
}
