//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rose.VExtension.Server.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LocalPluginFileSystem : PluginFileSystem
    {
        public string RootFolder { get; set; }
    }
}
