//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rose.VExtension.Server.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PluginAssociation
    {
        public int Id { get; set; }
        public string Seed { get; set; }
        public string PluginId { get; set; }
    }
}
