//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rose.VExtension.Server.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plugin
    {
        public Plugin()
        {
            this.ResourceTokens = new HashSet<ResourceToken>();
            this.StorageItems = new HashSet<StorageItem>();
            this.Test = new HashSet<Test>();
        }
    
        public string Id { get; set; }
        public string Name { get; set; }
        public PluginLocation Location { get; set; }
        public string Version { get; set; }
    
        public virtual ICollection<ResourceToken> ResourceTokens { get; set; }
        public virtual ICollection<StorageItem> StorageItems { get; set; }
        public virtual ICollection<Test> Test { get; set; }
        public virtual PluginFileSystem PluginFileSystem { get; set; }
        public virtual PluginPackage PluginPackage { get; set; }
    }
}
